apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-app
  template:
    metadata:
      labels:
        app: nexus-app
    spec:
      containers:
      - name: nexus-app
        image: nexus-app:latest
        ports:
        - containerPort: 8080