apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-ui
  template:
    metadata:
      labels:
        app: nexus-ui
    spec:
      containers:
      - name: nexus-ui
        image: nexus-ui:latest
        ports:
        - containerPort: 8080