apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-logic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-logic
  template:
    metadata:
      labels:
        app: nexus-logic
    spec:
      containers:
      - name: nexus-logic
        image: nexus-logic:latest
        ports:
        - containerPort: 8080