apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-web
  template:
    metadata:
      labels:
        app: nexus-web
    spec:
      containers:
      - name: nexus-web
        image: nexus-web:latest
        ports:
        - containerPort: 8080